version: "3"

networks:
  backend1:
    driver: bridge

services:

  php:
    container_name: php_${APP_NAME}
    build:
      context: ./
      dockerfile: docker/configs/php/Dockerfile
      args:
        WORKDIR: ${WORKDIR}
    environment:
      WORKDIR: ${WORKDIR}

    volumes:
      - ./:${WORKDIR}
    links:
      - db_mysql
    networks:
      - backend1

  db_mysql:
    image: mysql:latest
    container_name: mysql_${APP_NAME}
    ports:
      - ${DB_PORT}:3306
    environment:
      WORKDIR: ${WORKDIR}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_DATABASE:-root}
      MYSQL_USER: ${DB_USERNAME:-user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}

    volumes:
      - ./docker/databases/mysql_dump:/docker-entrypoint-initdb.d
    networks:
      - backend1

  nginx:
    image: nginx:latest
    container_name: nginx_${APP_NAME}
    environment:
      WORKDIR: ${WORKDIR}
      HTTP_PORT: ${HTTP_PORT}
      HTTPS_PORT: ${HTTPS_PORT}
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    volumes:
      - ./:${WORKDIR}
      - ./docker/configs/nginx:/etc/nginx/conf.d
      - ./docker/configs/nginx/project.conf.template:/etc/nginx/templates/project.conf.template
      - ./logs/nginx:/var/log/nginx
    links:
      - php
    networks:
      - backend1